framework:
  version: 1.0.0
loader:
  id_columns:
  - root_id
  - pre_root_id
  - post_root_id
preprocessing:
  features:
    indegree: true
    outdegree: true
    pagerank: true
runner:
  auto_export: false
statistics:
  confidence_level: 0.95
