"""
Phase TBD – False Synapses Error Model
=========================================
Implements the False Synapse (false-positive) perturbation model.

The model does **not** modify the baseline graph directly.  Instead it
produces an :class:`~modules.error_models.common.error_result.ErrorResult`
containing an ``added_edges`` list — a collection of ``(pre_root_id,
post_root_id, weight)`` tuples describing which false edges the
:class:`~core.experiment_runner.ExperimentRunner` should insert into the
temporary analysis graph.

Two-phase workflow:
    **Phase A (preprocessing, one-time):**
    :class:`~modules.preprocessing.false_synapses.candidate_generator.CandidateGenerator`
    builds a ranked candidate table from the baseline graph and caches it as
    ``candidates.parquet``.  Candidate generation is dataset-dependent and is
    performed once before any trials.

    **Phase B (perturbation, per trial):**
    :meth:`_perturb` loads the cached candidate table, samples *k* false edges
    (weighted by Jaccard similarity), assigns empirical weights, and records
    them in ``result.added_edges``.  The baseline graph is never touched.

The error rate is interpreted as the fraction of **new edges to add** relative
to the baseline edge count: ``k = round(error_rate × total_edges)``.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np
import polars as pl

from ..common.base_error_model import BaseErrorModel
from ..common.error_result import ErrorResult
from modules.preprocessing.common.prepared_graph import PreparedGraph
from modules.preprocessing.false_synapses.config import CACHE_DIR
from modules.error_models.false_synapses.weight_assignment import (
    get_empirical_weight_distribution,
    sample_false_weight,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Module-level cache for candidate table (shared across trials)
# ---------------------------------------------------------------------------

_candidate_table: Optional[pl.DataFrame] = None


def clear_candidate_cache() -> None:
    """Clear in-memory cached candidate table."""
    global _candidate_table
    _candidate_table = None


def _load_candidate_table(cache_path: Optional[Path] = None) -> pl.DataFrame:
    """Load the ranked candidate table from Parquet (cached in memory)."""
    global _candidate_table
    if _candidate_table is not None:
        return _candidate_table

    if cache_path is None:
        cache_path = Path(CACHE_DIR) / "candidates.parquet"

    target_path = Path(cache_path)
    if not target_path.exists() or not target_path.is_file():
        raise FileNotFoundError(
            f"Candidate table not found at '{target_path}'. "
            "Pass candidate_cache_path in error_model_config or run "
            "CandidateGenerator(prepared).generate() before attempting false-synapse perturbation."
        )

    _candidate_table = pl.read_parquet(str(target_path))
    logger.info(
        "[FalseSynapses] Loaded %s candidates from '%s'.",
        f"{len(_candidate_table):,}", target_path,
    )
    return _candidate_table


# ---------------------------------------------------------------------------
# FalseSynapseModel
# ---------------------------------------------------------------------------

class FalseSynapseModel(BaseErrorModel):
    """Perturbs a graph by adding false-positive (false-synapse) edges.

    The model samples candidate edges from a pre-computed ranked table
    (generated by :class:`~modules.preprocessing.false_synapses.candidate_generator.CandidateGenerator`),
    assigns empirically-derived synaptic weights, and returns the added edges
    via ``ErrorResult.added_edges``.

    The baseline graph is never copied or mutated.
    """

    NAME = "false_synapses"

    def _perturb(
        self,
        prepared: PreparedGraph,
        config: Dict[str, Any],
        result: ErrorResult,
        rng: np.random.Generator,
    ) -> None:
        """Execute the false-synapse perturbation.

        Args:
            prepared: The immutable baseline :class:`~modules.preprocessing.common.prepared_graph.PreparedGraph`.
            config:   Configuration dict containing ``error_rate``.
            result:   Pre-initialised :class:`~modules.error_models.common.error_result.ErrorResult`
                      to populate with ``added_edges``.
            rng:      NumPy random generator (seeded by the framework).

        Raises:
            FileNotFoundError: If the candidate table has not been generated.
            ValueError: If config values are invalid.
        """
        # --- Parse configuration ---
        error_rate = float(config.get("error_rate", 0.0))
        if not 0.0 <= error_rate <= 1.0:
            raise ValueError(
                f"[FalseSynapses] error_rate must be in [0.0, 1.0], got {error_rate}."
            )

        total_edges = prepared.graph.ecount()
        k = round(error_rate * total_edges)

        if k == 0:
            logger.info(
                "[FalseSynapses] error_rate=%.4f → no edges to add.",
                error_rate,
            )
            result.added_edges = []
            result.perturbation_metadata = {
                "error_rate": error_rate,
                "false_edges_added": 0,
                "candidates_available": 0,
            }
            return

        # --- Load candidate table ---
        cache_path_str = config.get("candidate_cache_path")
        cache_path = Path(cache_path_str) if cache_path_str else None
        candidates = _load_candidate_table(cache_path)

        if len(candidates) == 0:
            logger.warning(
                "[FalseSynapses] Candidate table is empty — no edges to add."
            )
            result.added_edges = []
            result.perturbation_metadata = {
                "error_rate": error_rate,
                "false_edges_added": 0,
                "candidates_available": 0,
            }
            return

        # --- Weighted random sample of k candidates ---
        # Higher Jaccard_out → higher sampling probability.
        weights = candidates["jaccard_out"].to_numpy()
        weights = np.clip(weights, 0.0, None)  # no negative weights
        weight_sum = weights.sum()

        if weight_sum <= 0:
            # Fall back to uniform sampling.
            weights = None

        # Sample without replacement from the top candidates.
        # Use a sampling pool of min(k * 2, len(candidates)) to avoid
        # sampling from the tail where candidates have negligible overlap.
        pool_size = min(len(candidates), max(k * 2, 1000))
        pool = candidates.head(pool_size)

        if pool_size < k:
            logger.warning(
                "[FalseSynapses] Candidate table has %d entries, but %d "
                "are requested. Adding all available candidates.",
                pool_size, k,
            )
            sample = pool
        else:
            sample_indices = rng.choice(
                pool_size,
                size=k,
                replace=False,
                p=weights[:pool_size] / weights[:pool_size].sum()
                if weights is not None
                else None,
            )
            sample = pool[sample_indices]

        # --- Assign weights + build added_edges ---
        weight_dist = get_empirical_weight_distribution(prepared)

        added = []
        for row in sample.iter_rows(named=True):
            weight = sample_false_weight(rng, weight_dist)
            added.append((
                int(row["pre_root_id"]),
                int(row["post_root_id"]),
                weight,
            ))

        result.added_edges = added
        result.perturbation_metadata = {
            "error_rate": error_rate,
            "false_edges_added": len(added),
            "candidates_available": len(candidates),
            "sampling_pool_size": pool_size,
        }

        logger.info(
            "[FalseSynapses] Added %d false edges (error_rate=%.4f, "
            "candidates available=%s).",
            len(added), error_rate, f"{len(candidates):,}",
        )


# ---------------------------------------------------------------------------
# Auto-registration
# ---------------------------------------------------------------------------

from ..common.error_registry import registry
registry.register(FalseSynapseModel, overwrite=True)
